logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
logging.level.root=${LOG_LEVEL:INFO}
logging.level.com.eazybytes.eazystore.controller.ProductController=INFO
logging.file.name=${LOG_FILE_NAME:/var/log/eazystore/app.log}
logging.pattern.file={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}

# Database Configuration (TiDB)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/eazystore/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.configprops.show-values=WHEN_AUTHORIZED
management.endpoint.env.show-values=WHEN_AUTHORIZED

# App Info
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Backend Project for Eazy Store E-commerce application
info.app.version=1.0.0
info.app.contact.email=4TtG3@example.com

# Contact Info
contact.phone=${CONTACT_PHONE:+91-1234567890}
contact.email=${CONTACT_EMAIL:dev@eazystore.com}
contact.address=${CONTACT_ADDRESS:123 Main Street, Anytown, USA}

# CORS
eazystore.cors.allowed-origins=${ALLOWED_ORIGINS:https://eazystore.vercel.app}

# Stripe
stripe.apiKey=${STRIPE_API_KEY}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expirationInMs=${JWT_EXPIRATION:86400000}
